version: "3.9"

services:
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: mlflow_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      
  mlflow:
    build: .
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri postgresql://username:password@postgres:5432/mlflow_db --default-artifact-root file://app/mlruns -h 0.0.0.0
    depends_on: 
      - postgres